// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzesvbaelaqpejrnavkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6ZXN2YmFlbGFxcGVqcm5hdmt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMDA0MDgsImV4cCI6MjA2MjU3NjQwOH0._fCuTW9kfPxjd0a7s0_ttHd4MWBjC7vOkPFIgdU2lUI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);